In [1]:
import pandas as pd

df = pd.read_csv("../data/cleaned_reviews.csv")

print(df.shape)

df.head()

d:\Anacoda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
d:\Anacoda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

(4915, 4)

,reviewText,overall,reviewTime,Sentiment
0,No issues.,4.0,2014-07-23,Positive
1,"Purchased this for my device, it worked as adv...",5.0,2013-10-25,Positive
2,it works as expected. I should have sprung for...,4.0,2012-12-23,Positive
3,This think has worked out great.Had a diff. br...,5.0,2013-11-21,Positive
4,"Bought it with Retail Packaging, arrived legit...",5.0,2013-07-13,Positive

In [2]:
import sys
sys.path.append("../src")

from text_normalizer import clean_text

df["clean_review"] = df["reviewText"].apply(clean_text)

df[["reviewText", "clean_review"]].head()

,reviewText,clean_review
0,No issues.,no issues
1,"Purchased this for my device, it worked as adv...",purchased this for my device it worked as adve...
2,it works as expected. I should have sprung for...,it works as expected i should have sprung for ...
3,This think has worked out great.Had a diff. br...,this think has worked out greathad a diff bran...
4,"Bought it with Retail Packaging, arrived legit...",bought it with retail packaging arrived legit ...

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X = tfidf.fit_transform(df["clean_review"])

print(X.shape)

(4915, 5000)

In [4]:
y = df["Sentiment"]

print(y.value_counts())

Sentiment
Positive    4449
Negative     324
Neutral      142
Name: count, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(3932, 5000)
(983, 5000)

In [6]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [7]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9257375381485249

In [8]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Negative       0.89      0.34      0.49        70
     Neutral       0.00      0.00      0.00        25
    Positive       0.93      1.00      0.96       888

    accuracy                           0.93       983
   macro avg       0.61      0.45      0.49       983
weighted avg       0.90      0.93      0.90       983

d:\Anacoda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Anacoda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Anacoda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])